# RNAGlib tasks

* RNA_Protein: residue level binary classification
* RNAGo: multi-class classification
* RNA_Ligand: pocket level multi-class classification
* RNA_Site: residue level binary classification

In [1]:
from rnaglib.tasks import (
    ChemicalModification, 
    RNAGo,
    InverseFolding,
    LigandIdentification,
    ProteinBindingSite,
    BenchmarkBindingSite,
    BindingSite,
)

import numpy as np
import os
import pandas as pd
import json
from collections import defaultdict
from Bio.PDB import PDBParser
from Bio.PDB.MMCIFParser import MMCIFParser
from tqdm import tqdm

DATA_DIR = "/n/holylfs06/LABS/mzitnik_lab/Lab/afang/ATOMICA/baselines/rnaglib_tasks"

/n/home13/afang/.conda/envs/rnaenv/lib/python3.10/site-packages/torch_geometric/__init__.py:4: UserWarning: An issue occurred while importing 'pyg-lib'. Disabling its usage. Stacktrace: Could not load this library: /n/home13/afang/.conda/envs/rnaenv/lib/python3.10/site-packages/libpyg.so
  import torch_geometric.typing
/n/home13/afang/.conda/envs/rnaenv/lib/python3.10/site-packages/torch_geometric/__init__.py:4: UserWarning: An issue occurred while importing 'torch-spline-conv'. Disabling its usage. Stacktrace: Could not load this library: /n/home13/afang/.conda/envs/rnaenv/lib/python3.10/site-packages/torch_spline_conv/_version_cuda.so
  import torch_geometric.typing
/n/home13/afang/.conda/envs/rnaenv/lib/python3.10/site-packages/torch_geometric/__init__.py:4: UserWarning: An issue occurred while importing 'torch-sparse'. Disabling its usage. Stacktrace: Could not load this library: /n/home13/afang/.conda/envs/rnaenv/lib/python3.10/site-packages/torch_sparse/_version_cuda.so
  import torch_geometric.typing
/n/home13/afang/.conda/envs/rnaenv/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

# ChemicalModification
Residue level task, Predict RNA residues with chemical modifications from geometry. This does not work at an atomic scale.

In [2]:
ta = ChemicalModification(
    root=f"{DATA_DIR}/RNA_CM",
    recompute=False,
    debug=False,
)
train, val, test = ta.get_split_datasets(recompute=False)
len(train), len(val), len(test)

>>> Loading precomputed task...
>>> Splitting the dataset...
>>> Done

(138, 29, 30)

In [6]:
train[0]

{'rna': <networkx.classes.digraph.DiGraph at 0x14563a797e80>,
 'graph_path': PosixPath('/n/holylfs06/LABS/mzitnik_lab/Lab/afang/ATOMICA/baselines/rnaglib_tasks/RNA_CM/dataset/1b23_0.json'),
 'cif_path': None}

In [3]:
train[0]['rna'].nodes

NodeView(('1b23.R.2', '1b23.R.1', '1b23.R.3', '1b23.R.4', '1b23.R.5', '1b23.R.6', '1b23.R.7', '1b23.R.8', '1b23.R.9', '1b23.R.10', '1b23.R.11', '1b23.R.12', '1b23.R.13', '1b23.R.14', '1b23.R.15', '1b23.R.16', '1b23.R.19', '1b23.R.18', '1b23.R.20', '1b23.R.21', '1b23.R.22', '1b23.R.23', '1b23.R.24', '1b23.R.25', '1b23.R.26', '1b23.R.27', '1b23.R.28', '1b23.R.29', '1b23.R.30', '1b23.R.31', '1b23.R.32', '1b23.R.33', '1b23.R.34', '1b23.R.35', '1b23.R.36', '1b23.R.37', '1b23.R.38', '1b23.R.39', '1b23.R.40', '1b23.R.41', '1b23.R.42', '1b23.R.43', '1b23.R.44', '1b23.R.45', '1b23.R.46', '1b23.R.49', '1b23.R.48', '1b23.R.50', '1b23.R.51', '1b23.R.52', '1b23.R.53', '1b23.R.54', '1b23.R.55', '1b23.R.56', '1b23.R.57', '1b23.R.58', '1b23.R.59', '1b23.R.60', '1b23.R.61', '1b23.R.62', '1b23.R.63', '1b23.R.64', '1b23.R.65', '1b23.R.66', '1b23.R.67', '1b23.R.68', '1b23.R.69', '1b23.R.70', '1b23.R.71', '1b23.R.72', '1b23.R.73', '1b23.R.74', '1b23.R.75', '1b23.R.76'))

In [8]:
train[0]

{'rna': <networkx.classes.digraph.DiGraph at 0x15438cdf2b90>,
 'graph_path': PosixPath('/n/holylfs06/LABS/mzitnik_lab/Lab/afang/ATOMICA/baselines/rnaglib_tasks/RNA_CM/dataset/1b23_0.json'),
 'cif_path': None}

In [10]:
fc = ta.dataset.features_computer

In [13]:
fc(train[0])['nt_targets']

{'1b23.R.2': tensor([0.]),
 '1b23.R.1': tensor([0.]),
 '1b23.R.3': tensor([0.]),
 '1b23.R.4': tensor([0.]),
 '1b23.R.5': tensor([0.]),
 '1b23.R.6': tensor([0.]),
 '1b23.R.7': tensor([0.]),
 '1b23.R.8': tensor([1.]),
 '1b23.R.9': tensor([0.]),
 '1b23.R.10': tensor([0.]),
 '1b23.R.11': tensor([0.]),
 '1b23.R.12': tensor([0.]),
 '1b23.R.13': tensor([0.]),
 '1b23.R.14': tensor([0.]),
 '1b23.R.15': tensor([0.]),
 '1b23.R.16': tensor([0.]),
 '1b23.R.19': tensor([0.]),
 '1b23.R.18': tensor([0.]),
 '1b23.R.20': tensor([1.]),
 '1b23.R.21': tensor([1.]),
 '1b23.R.22': tensor([0.]),
 '1b23.R.23': tensor([0.]),
 '1b23.R.24': tensor([0.]),
 '1b23.R.25': tensor([0.]),
 '1b23.R.26': tensor([0.]),
 '1b23.R.27': tensor([0.]),
 '1b23.R.28': tensor([0.]),
 '1b23.R.29': tensor([0.]),
 '1b23.R.30': tensor([0.]),
 '1b23.R.31': tensor([0.]),
 '1b23.R.32': tensor([1.]),
 '1b23.R.33': tensor([0.]),
 '1b23.R.34': tensor([0.]),
 '1b23.R.35': tensor([0.]),
 '1b23.R.36': tensor([0.]),
 '1b23.R.37': tensor([1.]),
 '1b23.R.38': tensor([0.]),
 '1b23.R.39': tensor([1.]),
 '1b23.R.40': tensor([0.]),
 '1b23.R.41': tensor([0.]),
 '1b23.R.42': tensor([0.]),
 '1b23.R.43': tensor([0.]),
 '1b23.R.44': tensor([0.]),
 '1b23.R.45': tensor([0.]),
 '1b23.R.46': tensor([0.]),
 '1b23.R.49': tensor([0.]),
 '1b23.R.48': tensor([0.]),
 '1b23.R.50': tensor([0.]),
 '1b23.R.51': tensor([0.]),
 '1b23.R.52': tensor([0.]),
 '1b23.R.53': tensor([0.]),
 '1b23.R.54': tensor([1.]),
 '1b23.R.55': tensor([1.]),
 '1b23.R.56': tensor([0.]),
 '1b23.R.57': tensor([0.]),
 '1b23.R.58': tensor([0.]),
 '1b23.R.59': tensor([0.]),
 '1b23.R.60': tensor([0.]),
 '1b23.R.61': tensor([0.]),
 '1b23.R.62': tensor([0.]),
 '1b23.R.63': tensor([0.]),
 '1b23.R.64': tensor([0.]),
 '1b23.R.65': tensor([0.]),
 '1b23.R.66': tensor([0.]),
 '1b23.R.67': tensor([0.]),
 '1b23.R.68': tensor([0.]),
 '1b23.R.69': tensor([0.]),
 '1b23.R.70': tensor([0.]),
 '1b23.R.71': tensor([0.]),
 '1b23.R.72': tensor([0.]),
 '1b23.R.73': tensor([0.]),
 '1b23.R.74': tensor([0.]),
 '1b23.R.75': tensor([0.]),
 '1b23.R.76': tensor([0.])}

# RNAGo - TODO
Classify RNAs into one or more frequent function. Multi-class classification (5).

label_mapping = {"0000353": 0, "0005682": 1, "0005686": 2, "0005688": 3, "0010468": 4}

In [2]:
ta = RNAGo(
    root=f"{DATA_DIR}/RNAGo",
    recompute=False,
    debug=False,
)
train, val, test = ta.get_split_datasets(recompute=False)
fc = ta.dataset.features_computer
len(train), len(val), len(test)

>>> Loading precomputed task...
>>> Splitting the dataset...
>>> Done

(349, 75, 75)

In [30]:
for split_name, split in zip(["train", "val", "test"], [train, val, test]):
    targets = []
    for item in split: 
        targets.append(fc(item)['rna_targets'])
    targets = np.array(targets)
    print(split_name, np.sum(targets, axis=0))
    print("number of samples that belong to no class", (np.sum(targets, axis=-1).flatten() == 0).sum(), len(targets)) # how many belong to no class

train [[127.  71.  50.  50.  75.]]
number of samples that belong to no class 97 349
val [[32.  3. 10. 27.  5.]]
number of samples that belong to no class 28 75
test [[ 8.  7. 11.  1. 20.]]
number of samples that belong to no class 36 75

In [22]:
for split, dataset_split in zip(["train", "val", "test"], [train, val, test]):
    pdb_to_process = []
    for item in dataset_split:
        item_graph = vars(item['rna'])['graph']
        nodes = list(item['rna'].nodes)
        pdb_indexes = []
        chains = []
        for node in nodes:
            _, chain, res_id = node.split(".")
            pdb_indexes.append(f'{chain}_{res_id}')
            chains.append(chain)
        item_to_process = {
            "pdb_id": item_graph['name'],
            "pdb_path": f'{DATA_DIR}/pdbs/{item_graph["pdbid"]}.cif',
            "chain1": ",".join(sorted(set(chains))),
            "pdb_indexes": pdb_indexes,
            "label": fc(item)['rna_targets'][0].tolist(),
        }
        pdb_to_process.append(item_to_process)
    pdb_to_process = pd.DataFrame(pdb_to_process)
    pdb_to_process.to_parquet(f'{DATA_DIR}/RNAGo/RNAGo_{split}_input.parquet')

In [2]:
# Prepare RNAFM data
embeddings_dir = DATA_DIR + "/RNAGo"
model_name = "rinalmo"

for split in ["train", "val", "test"]:
    split_df = pd.read_parquet(f'{DATA_DIR}/RNAGo/RNAGo_{split}_input.parquet')
    split_df.head()

    # Load embeddings
    embeddings_df = pd.read_parquet(f'{DATA_DIR}/RNAGo/RNAGo_sequences.parquet')
    embeddings_path = f"{embeddings_dir}/RNAGo_embeddings_{model_name}.npy"
    tokens_path = f"{embeddings_dir}/RNAGo_tokens_{model_name}.npy"
    with open(embeddings_path, "rb") as f:
        embeddings = np.load(f)
    with open(tokens_path, "rb") as f:
        tokens = np.load(f)
    assert tokens.shape == embeddings.shape[:-1], f"{tokens.shape} != {embeddings.shape[:-1]}"
    assert len(embeddings) == len(embeddings_df)

    embeddings_id_to_index = {(row['pdb_id'], row['chain_id']): i for i, row in embeddings_df.iterrows()}

    # Extract embeddings for each split
    split_embeddings = []
    for i, row in split_df.iterrows():
        pdb_id = row['pdb_id'].split("_")[0]
        chain_id = row['chain1']
        index = embeddings_id_to_index[(pdb_id, chain_id)]
        embedding_ = embeddings[index]
        tokens_ = tokens[index]
        # start = np.where(tokens_ == 0)[0][0]
        end = np.where(tokens_ == 2)[0][0]
        split_embeddings.append(np.mean(embedding_[:end], axis=0))
    split_embeddings = np.array(split_embeddings)
    assert len(split_embeddings) == len(split_df)
    labels = np.stack(split_df['label'].tolist())

    np.save(f'{DATA_DIR}/RNAGo/RNAGo_{split}_embeddings_{model_name}.npy', split_embeddings)
    np.save(f'{DATA_DIR}/RNAGo/RNAGo_{split}_labels_{model_name}.npy', labels)

# RNA IF
Find a sequence that folds into this structure. Residue-level task. Also don't think this task is suitable, since we already do masked residue prediction.

In [24]:
ta = InverseFolding(
    root=f"{DATA_DIR}/RNA_IF",
    recompute=False,
    debug=False,
)
train, val, test = ta.get_split_datasets(recompute=False)
fc = ta.dataset.features_computer
len(train), len(val), len(test)

>>> Loading precomputed task...
>>> Splitting the dataset...

>>> Done

(1700, 448, 581)

# RNA Protein - TODO
Predict RNA residues interacting with a protein. Residue-level binary classification task.

In [5]:
ta = ProteinBindingSite(
    root=f"{DATA_DIR}/RNA_Protein",
    recompute=False,
    debug=False,
)
train, val, test = ta.get_split_datasets(recompute=False)
fc = ta.dataset.features_computer

len(train), len(val), len(test)

>>> Loading precomputed task...
>>> Splitting the dataset...
>>> Done

(892, 191, 191)

In [51]:
for split, dataset_split in zip(["train", "val", "test"], [train, val, test]):
    pdb_to_process = []
    for item in dataset_split:
        item_graph = vars(item['rna'])['graph']
        nodes = fc(item)['nt_targets']
        pdb_indexes = []
        chains = []
        labels = []
        for node, label in nodes.items():
            _, chain, res_id = node.split(".")
            pdb_indexes.append(f'{chain}_{res_id}')
            chains.append(chain)
            labels.append(label.item())
        item_to_process = {
            "pdb_id": item_graph['name'],
            "pdb_path": f'{DATA_DIR}/pdbs/{item_graph["pdbid"]}.cif',
            "chain1": ",".join(sorted(set(chains))),
            "pdb_indexes": pdb_indexes,
            "label": labels,
        }
        pdb_to_process.append(item_to_process)
    pdb_to_process = pd.DataFrame(pdb_to_process)
    pdb_to_process.to_parquet(f'{DATA_DIR}/RNA_Protein/RNA_Protein_{split}_input.parquet')

In [52]:
df = pd.read_parquet(f'{DATA_DIR}/RNA_Protein/RNA_Protein_{split}_input.parquet')
df

,pdb_id,pdb_path,chain1,pdb_indexes,label
0,1et4_0,/n/holylfs06/LABS/mzitnik_lab/Lab/afang/ATOMIC...,"A,B","[A_231, A_234, A_219, A_206, A_204, B_317, A_2...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
1,1f1t_0,/n/holylfs06/LABS/mzitnik_lab/Lab/afang/ATOMIC...,A,"[A_2, A_1, A_3, A_4, A_5, A_6, A_7, A_8, A_9, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
2,1hys_0,/n/holylfs06/LABS/mzitnik_lab/Lab/afang/ATOMIC...,E,"[E_855, E_854, E_856, E_857, E_858, E_859, E_8...","[1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, ..."
3,1i6u_0,/n/holylfs06/LABS/mzitnik_lab/Lab/afang/ATOMIC...,C,"[C_2, C_1, C_3, C_4, C_5, C_6, C_7, C_8, C_9, ...","[0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, ..."
4,1j2b_0,/n/holylfs06/LABS/mzitnik_lab/Lab/afang/ATOMIC...,C,"[C_902, C_901, C_903, C_904, C_905, C_906, C_9...","[0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, ..."
...,...,...,...,...,...
186,9g6k_0,/n/holylfs06/LABS/mzitnik_lab/Lab/afang/ATOMIC...,l0,"[l0_30, l0_24, l0_22, l0_53, l0_19, l0_45, l0_...","[1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, ..."
187,9g6k_2,/n/holylfs06/LABS/mzitnik_lab/Lab/afang/ATOMIC...,"l2,lG","[l2_21, l2_16, lG_22, l2_3, lG_19, lG_3, l2_15...","[1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, ..."
188,9g6k_4,/n/holylfs06/LABS/mzitnik_lab/Lab/afang/ATOMIC...,lE,"[lE_29, lE_21, lE_25, lE_11, lE_19, lE_3, lE_1...","[1.0, 1.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, ..."
189,9gs9_0,/n/holylfs06/LABS/mzitnik_lab/Lab/afang/ATOMIC...,1,"[1_2, 1_1, 1_3, 1_4, 1_5, 1_6, 1_7, 1_8, 1_9, ...","[1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, ..."
190,9ij0_0,/n/holylfs06/LABS/mzitnik_lab/Lab/afang/ATOMIC...,"B,C","[B_2, B_1, B_3, B_4, B_5, B_6, B_7, B_8, B_9, ...","[1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, ..."

In [30]:
embeddings_df

,pdb_id,chain_id,seq,residues
0,5xjc,H,AUCGCUUCUCGGCCUUUUGGCUAAGAUCAAGUGUAGUAUCUGUUCU...,"[5xjc.H.1, 5xjc.H.2, 5xjc.H.3, 5xjc.H.4, 5xjc...."
1,5xjc,B,GGUUUCUCUUCAGAUCGCAUAAAUCUUUCGCCUUUUACUAAAGAUU...,"[5xjc.B.8, 5xjc.B.9, 5xjc.B.10, 5xjc.B.11, 5xj..."
2,5xjc,F,GUGCUCGCUUCGGCAGCACAUAUACUAAAAUUGGAACGAUACAGAG...,"[5xjc.F.1, 5xjc.F.2, 5xjc.F.3, 5xjc.F.4, 5xjc...."
3,8i0r,H,AUCGCUUCUCGGCCUUUUGGCUAAGAUCAAGUGUAGUAUCUGUUCU...,"[8i0r.H.1, 8i0r.H.2, 8i0r.H.3, 8i0r.H.4, 8i0r...."
4,8i0r,B,GGUUUCUCUUCAGAUCGCAUAAAUCUUUCGCCUUUUACUAAAGAUU...,"[8i0r.B.8, 8i0r.B.9, 8i0r.B.10, 8i0r.B.11, 8i0..."
...,...,...,...,...
464,3q3z,V,-CGCGGAAACAAUGAUGAAUGGGUUUAAAUUGGGCACUUGACUCAU...,"[3q3z.V.7, 3q3z.V.8, 3q3z.V.9, 3q3z.V.10, 3q3z..."
465,5j02,A,GUGUGCCCGGCAUGGGUGCAGUCUAUAGGGUGAGAGUCCCGAACUG...,"[5j02.A.1, 5j02.A.2, 5j02.A.3, 5j02.A.4, 5j02...."
466,6jq5,B,UUACUGUGAGAAUCAGUAACAAACAUGUGGGGCUUAUAUCUAAUCG...,"[6jq5.B.1, 6jq5.B.2, 6jq5.B.3, 6jq5.B.4, 6jq5...."
467,6jq5,A,UUACUGUGAGAAUCAGUAACAAACAUGUGGGGCUUAUAUCUAAUCG...,"[6jq5.A.1, 6jq5.A.2, 6jq5.A.3, 6jq5.A.4, 6jq5...."
468,6jq6,U,UUACUGUGAGAAUCAGUAACAAACAUGUGGGGCUUAUAUCUAAUCU...,"[6jq6.U.1, 6jq6.U.2, 6jq6.U.3, 6jq6.U.4, 6jq6...."

In [4]:
# Prepare RNAFM data
# The RNAErnie data is in scratch, needs to be moved to DATA_DIR
embeddings_dir = DATA_DIR + "/RNA_Protein"
model_name = "rinalmo"

for split in ["train", "val", "test"]:
    split_df = pd.read_parquet(f'{DATA_DIR}/RNA_Protein/RNA_Protein_{split}_input.parquet')
    split_df.head()

    # Load embeddings
    embeddings_df = pd.read_parquet(f'{DATA_DIR}/RNA_Protein/RNA_Protein_sequences.parquet')
    embeddings_path = f"{embeddings_dir}/RNA_Protein_embeddings_{model_name}.npy"
    tokens_path = f"{embeddings_dir}/RNA_Protein_tokens_{model_name}.npy"
    with open(embeddings_path, "rb") as f:
        embeddings = np.load(f)
    with open(tokens_path, "rb") as f:
        tokens = np.load(f)
    assert tokens.shape == embeddings.shape[:-1]
    assert len(embeddings) == len(embeddings_df)

    embeddings_id_to_index = {(row['pdb_id'], row['chain_id']): i for i, row in embeddings_df.iterrows()}

    # Extract embeddings for each split
    split_embeddings = []
    labels = []
    for i, row in tqdm(split_df.iterrows(), total=len(split_df)):
        pdb_id = row['pdb_id'].split("_")[0]
        rnafm_embeddings = {}
        for chain_id in row['chain1'].split(","):
            index = embeddings_id_to_index[(pdb_id, chain_id)]
            embedding_ = embeddings[index]
            tokens_ = tokens[index]
            # start = np.where(tokens_ == 0)[0][0]
            end = np.where(tokens_ == 2)[0][0]

            embedding_ = embedding_[:end]
            residues = embeddings_df.iloc[index]['residues']
            assert len(embedding_) == len(residues) or len(embedding_) == len(residues) + 1
            for residue, embedding in zip(residues, embedding_):
                residue_id = residue[5:].replace(".", "_")
                rnafm_embeddings[residue_id] = embedding

        assert len(row['pdb_indexes']) == len(row['label'])
        for pdb_index, label in zip(row['pdb_indexes'], row['label']):
            try:
                split_embeddings.append(rnafm_embeddings[pdb_index])
                labels.append(label)
            except KeyError:
                print("Missing", pdb_id, pdb_index)
        
    split_embeddings = np.array(split_embeddings)
    labels = np.array(labels)
    assert len(split_embeddings) == len(labels)

    np.save(f'{DATA_DIR}/RNA_Protein/RNA_Protein_{split}_embeddings_{model_name}.npy', split_embeddings)
    np.save(f'{DATA_DIR}/RNA_Protein/RNA_Protein_{split}_labels_{model_name}.npy', labels)

:

# RNA Site - TODO
Predict RNA residues interacting with a small-molecule protein.

In [53]:
# This is the dataset used in an existing paper
ta = BenchmarkBindingSite(
    root=f"{DATA_DIR}/Benchmark_RNA_Site",
    recompute=False,
    debug=False,
)
train, val, test = ta.get_split_datasets(recompute=False)
fc = ta.dataset.features_computer

len(train), len(val), len(test)

>>> Loading precomputed task...
>>> Splitting the dataset...
>>> Done

(53, 6, 17)

In [54]:
# This is the larger updated dataset
ta = BindingSite(
    root=f"{DATA_DIR}/RNA_Site",
    recompute=False,
    debug=False,
)
train, val, test = ta.get_split_datasets(recompute=False)
fc = ta.dataset.features_computer

len(train), len(val), len(test)

>>> Loading precomputed task...
>>> Splitting the dataset...
>>> Done

(157, 34, 33)

In [55]:
for split, dataset_split in zip(["train", "val", "test"], [train, val, test]):
    pdb_to_process = []
    for item in dataset_split:
        item_graph = vars(item['rna'])['graph']
        nodes = fc(item)['nt_targets']
        pdb_indexes = []
        chains = []
        labels = []
        for node, label in nodes.items():
            _, chain, res_id = node.split(".")
            pdb_indexes.append(f'{chain}_{res_id}')
            chains.append(chain)
            labels.append(label.item())
        item_to_process = {
            "pdb_id": item_graph['name'],
            "pdb_path": f'{DATA_DIR}/pdbs/{item_graph["pdbid"]}.cif',
            "chain1": ",".join(sorted(set(chains))),
            "pdb_indexes": pdb_indexes,
            "label": labels,
        }
        pdb_to_process.append(item_to_process)
    pdb_to_process = pd.DataFrame(pdb_to_process)
    pdb_to_process.to_parquet(f'{DATA_DIR}/RNA_Site/RNA_Site_{split}_input.parquet')

In [5]:
split = "train"
df = pd.read_parquet(f'{DATA_DIR}/RNA_Site/RNA_Site_{split}_input.parquet')
df

,pdb_id,pdb_path,chain1,pdb_indexes,label
0,1a34_0,/n/holylfs06/LABS/mzitnik_lab/Lab/afang/ATOMIC...,"B,C","[B_2, B_1, B_3, B_4, B_5, B_6, B_7, B_8, B_9, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, ..."
1,1asz_0,/n/holylfs06/LABS/mzitnik_lab/Lab/afang/ATOMIC...,R,"[R_602, R_601, R_603, R_604, R_605, R_606, R_6...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
2,1c0a_0,/n/holylfs06/LABS/mzitnik_lab/Lab/afang/ATOMIC...,B,"[B_602, B_601, B_603, B_604, B_605, B_606, B_6...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
3,1dk1_0,/n/holylfs06/LABS/mzitnik_lab/Lab/afang/ATOMIC...,B,"[B_2, B_1, B_3, B_4, B_5, B_6, B_7, B_8, B_9, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
4,1drz_0,/n/holylfs06/LABS/mzitnik_lab/Lab/afang/ATOMIC...,B,"[B_102, B_101, B_103, B_104, B_105, B_106, B_1...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
...,...,...,...,...,...
152,8z8x_0,/n/holylfs06/LABS/mzitnik_lab/Lab/afang/ATOMIC...,"D,E","[D_2, D_1, D_3, D_4, D_5, D_6, D_7, D_8, D_9, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
153,8z97_2,/n/holylfs06/LABS/mzitnik_lab/Lab/afang/ATOMIC...,"F,G","[F_6, F_5, F_7, F_8, F_9, F_10, F_11, F_12, F_...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
154,9gat_0,/n/holylfs06/LABS/mzitnik_lab/Lab/afang/ATOMIC...,O,"[O_17, O_3, O_14, O_4, O_10, O_15, O_16, O_8, ...","[1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, ..."
155,9imb_0,/n/holylfs06/LABS/mzitnik_lab/Lab/afang/ATOMIC...,D,"[D_2, D_1, D_3, D_4, D_5, D_6, D_7, D_8, D_9, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
156,9jm0_1,/n/holylfs06/LABS/mzitnik_lab/Lab/afang/ATOMIC...,"H,I","[H_11, I_0, H_45, H_61, H_60, I_2, I_6, H_72, ...","[0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."

In [ ]:
# Prepare RNAFM data
# only keep the pocket residues
model_name = "rinalmo"

for split in ["train", "val", "test"]:
    split_df = pd.read_parquet(f'{DATA_DIR}/RNA_Site/RNA_Site_{split}_input.parquet')
    split_df.head()

    # Load embeddings
    embeddings_df = pd.read_parquet(f'{DATA_DIR}/RNA_Site/RNA_Site_sequences.parquet')
    embeddings_path = f"{DATA_DIR}/RNA_Site/RNA_Site_embeddings_{model_name}.npy"
    tokens_path = f"{DATA_DIR}/RNA_Site/RNA_Site_tokens_{model_name}.npy"
    with open(embeddings_path, "rb") as f:
        embeddings = np.load(f)
    with open(tokens_path, "rb") as f:
        tokens = np.load(f)
    assert tokens.shape == embeddings.shape[:-1]
    assert len(embeddings) == len(embeddings_df)

    embeddings_id_to_index = {(row['pdb_id'], row['chain_id']): i for i, row in embeddings_df.iterrows()}

    # Extract embeddings for each split
    split_embeddings = []
    labels = []
    for i, row in tqdm(split_df.iterrows(), total=len(split_df)):
        pdb_id = row['pdb_id'].split("_")[0]
        rnafm_embeddings = {}
        for chain_id in row['chain1'].split(","):
            index = embeddings_id_to_index[(pdb_id, chain_id)]
            embedding_ = embeddings[index]
            tokens_ = tokens[index]
            # start = np.where(tokens_ == 0)[0][0]
            end = np.where(tokens_ == 2)[0][0]
            embedding_ = embedding_[:end]
            residues = embeddings_df.iloc[index]['residues']
            # For some we include the CLS token, for others we don't
            assert len(embedding_) == len(residues) + 1 or len(embedding_) == len(residues)
            for residue, embedding in zip(residues, embedding_):
                residue_id = residue[5:].replace(".", "_")
                rnafm_embeddings[residue_id] = embedding

        assert len(row['pdb_indexes']) == len(row['label'])
        for pdb_index, label in zip(row['pdb_indexes'], row['label']):
            try:
                split_embeddings.append(rnafm_embeddings[pdb_index])
                labels.append(label)
            except KeyError:
                print("Missing", pdb_id, pdb_index)
        
    split_embeddings = np.array(split_embeddings)
    labels = np.array(labels)
    assert len(split_embeddings) == len(labels)

    np.save(f'{DATA_DIR}/RNA_Site/RNA_Site_{split}_embeddings_{model_name}.npy', split_embeddings)
    np.save(f'{DATA_DIR}/RNA_Site/RNA_Site_{split}_labels_{model_name}.npy', labels)

100%|██████████| 157/157 [00:00<00:00, 5044.90it/s]
100%|██████████| 34/34 [00:00<00:00, 2897.50it/s]
100%|██████████| 33/33 [00:00<00:00, 2721.16it/s]

# RNA Ligand - TODO 
Classify binding sites by ligand type. Pocket level, multi-class classification (3).

The ligands are: 
* Paromycin (PAR)
* Gentamycin C1A (LLL)
* Aminoglycoside TC007 (8UZ)

In [6]:
ta = LigandIdentification(
    root=f"{DATA_DIR}/RNA_Ligand",
    recompute=False,
    debug=False,
)
train, val, test = ta.get_split_datasets(recompute=False)
fc = ta.dataset.features_computer
len(train), len(val), len(test)

>>> Loading precomputed task...
>>> Splitting the dataset...
>>> Done

(203, 43, 44)

In [7]:
for split_name, split in zip(["train", "val", "test"], [train, val, test]):
    labels = []
    for item in split:
        label = fc(item)['rna_targets']
        labels.append(label)

    labels = np.array(labels)
    print(split_name, np.unique(labels, return_counts=True))

train (array([0, 1, 2]), array([137,  20,  46]))
val (array([0, 1, 2]), array([29,  4, 10]))
test (array([0, 1, 2]), array([29,  5, 10]))

In [59]:
for split, dataset_split in zip(["train", "val", "test"], [train, val, test]):
    pdb_to_process = []
    for item in dataset_split:
        item_graph = vars(item['rna'])['graph']
        nodes = list(item['rna'].nodes)
        pdb_indexes = []
        chains = []
        for node in nodes:
            _, chain, res_id = node.split(".")
            pdb_indexes.append(f'{chain}_{res_id}')
            chains.append(chain)
        item_to_process = {
            "pdb_id": item_graph['name'],
            "pdb_path": f'{DATA_DIR}/pdbs/{item_graph["pdbid"]}.cif',
            "chain1": ",".join(sorted(set(chains))),
            "pdb_indexes": pdb_indexes,
            "label": fc(item)['rna_targets'].item(),
        }
        pdb_to_process.append(item_to_process)
    pdb_to_process = pd.DataFrame(pdb_to_process)
    pdb_to_process.to_parquet(f'{DATA_DIR}/RNA_Ligand/RNA_Ligand_{split}_input.parquet')

In [60]:
pdb_to_process

,pdb_id,pdb_path,chain1,pdb_indexes,label
0,4dr2_2,/n/holylfs06/LABS/mzitnik_lab/Lab/afang/ATOMIC...,A,"[A_115, A_893, A_240, A_119, A_894, A_127, A_2...",1
1,4dr2_5,/n/holylfs06/LABS/mzitnik_lab/Lab/afang/ATOMIC...,A,"[A_290, A_620, A_622, A_401, A_623, A_294, A_4...",1
2,4dr2_11,/n/holylfs06/LABS/mzitnik_lab/Lab/afang/ATOMIC...,A,"[A_602, A_634, A_637, A_639, A_633, A_635, A_5...",1
3,4dr2_12,/n/holylfs06/LABS/mzitnik_lab/Lab/afang/ATOMIC...,A,"[A_104, A_151, A_169, A_150, A_69, A_89, A_61,...",1
4,4dr2_14,/n/holylfs06/LABS/mzitnik_lab/Lab/afang/ATOMIC...,A,"[A_602, A_290, A_634, A_637, A_633, A_635, A_2...",1
5,4dr2_15,/n/holylfs06/LABS/mzitnik_lab/Lab/afang/ATOMIC...,A,"[A_290, A_634, A_633, A_294, A_308, A_565, A_2...",1
6,4dr2_16,/n/holylfs06/LABS/mzitnik_lab/Lab/afang/ATOMIC...,A,"[A_426, A_406, A_433, A_434, A_423, A_413, A_4...",1
7,4dr4_5,/n/holylfs06/LABS/mzitnik_lab/Lab/afang/ATOMIC...,A,"[A_44, A_45, A_614, A_42, A_304, A_41, A_609, ...",1
8,4dr4_13,/n/holylfs06/LABS/mzitnik_lab/Lab/afang/ATOMIC...,A,"[A_289, A_614, A_310, A_304, A_609, A_294, A_6...",1
9,4woi_3,/n/holylfs06/LABS/mzitnik_lab/Lab/afang/ATOMIC...,BA,"[BA_553, BA_532, BA_556, BA_549, BA_560, BA_11...",1
10,4woi_8,/n/holylfs06/LABS/mzitnik_lab/Lab/afang/ATOMIC...,CA,"[CA_560, CA_543, CA_991, CA_557, CA_1159, CA_5...",1
11,5br8_4,/n/holylfs06/LABS/mzitnik_lab/Lab/afang/ATOMIC...,A,"[A_612, A_293, A_400, A_402, A_42, A_615, A_61...",1
12,5ndv_0,/n/holylfs06/LABS/mzitnik_lab/Lab/afang/ATOMIC...,1,"[1_113, 1_154, 1_163, 1_166, 1_252, 1_255, 1_1...",1
13,5ndv_5,/n/holylfs06/LABS/mzitnik_lab/Lab/afang/ATOMIC...,1,"[1_2560, 1_1561, 1_1808, 1_1578, 1_1649, 1_182...",1
14,5ndv_11,/n/holylfs06/LABS/mzitnik_lab/Lab/afang/ATOMIC...,1,"[1_1103, 1_2638, 1_1067, 1_995, 1_982, 1_990, ...",1
15,5ndv_12,/n/holylfs06/LABS/mzitnik_lab/Lab/afang/ATOMIC...,"1,3","[3_102, 3_82, 1_2638, 3_98, 1_995, 3_103, 1_10...",1
16,5ndv_23,/n/holylfs06/LABS/mzitnik_lab/Lab/afang/ATOMIC...,1,"[1_1777, 1_1774, 1_1775, 1_1695, 1_1751, 1_169...",1
17,5ndv_41,/n/holylfs06/LABS/mzitnik_lab/Lab/afang/ATOMIC...,"1,4","[4_41, 4_46, 4_107, 1_21, 4_137, 4_42, 4_113, ...",1
18,5ndv_45,/n/holylfs06/LABS/mzitnik_lab/Lab/afang/ATOMIC...,2,"[2_1072, 2_1036, 2_1052, 2_1069, 2_1092, 2_103...",1
19,5ndv_80,/n/holylfs06/LABS/mzitnik_lab/Lab/afang/ATOMIC...,"5,8","[8_7, 5_2377, 8_10, 5_2363, 5_655, 5_417, 8_15...",1
20,5ndv_81,/n/holylfs06/LABS/mzitnik_lab/Lab/afang/ATOMIC...,6,"[6_430, 6_411, 6_48, 6_57, 6_410, 6_407, 6_423...",1
21,5ndv_85,/n/holylfs06/LABS/mzitnik_lab/Lab/afang/ATOMIC...,6,"[6_1062, 6_1036, 6_1076, 6_1094, 6_1081, 6_103...",1
22,5ndw_0,/n/holylfs06/LABS/mzitnik_lab/Lab/afang/ATOMIC...,1,"[1_226, 1_185, 1_227, 1_212, 1_190, 1_187, 1_2...",2
23,5ndw_3,/n/holylfs06/LABS/mzitnik_lab/Lab/afang/ATOMIC...,1,"[1_3146, 1_3002, 1_3160, 1_3000, 1_3142, 1_328...",2
24,5ndw_5,/n/holylfs06/LABS/mzitnik_lab/Lab/afang/ATOMIC...,1,"[1_816, 1_920, 1_2136, 1_924, 1_926, 1_910, 1_...",2
25,5ndw_9,/n/holylfs06/LABS/mzitnik_lab/Lab/afang/ATOMIC...,1,"[1_3195, 1_3192, 1_3190, 1_3185, 1_3208, 1_318...",2
26,5ndw_18,/n/holylfs06/LABS/mzitnik_lab/Lab/afang/ATOMIC...,5,"[5_2140, 5_906, 5_917, 5_2137, 5_2136, 5_2975,...",2
27,5obm_4,/n/holylfs06/LABS/mzitnik_lab/Lab/afang/ATOMIC...,1,"[1_907, 1_2809, 1_921, 1_883, 1_2820, 1_2808, ...",0
28,5obm_8,/n/holylfs06/LABS/mzitnik_lab/Lab/afang/ATOMIC...,1,"[1_3298, 1_3389, 1_3316, 1_3383, 1_3388, 1_331...",0
29,5obm_9,/n/holylfs06/LABS/mzitnik_lab/Lab/afang/ATOMIC...,"1,4","[4_117, 4_109, 4_142, 4_135, 4_107, 4_41, 4_10...",0
30,5obm_18,/n/holylfs06/LABS/mzitnik_lab/Lab/afang/ATOMIC...,1,"[1_3372, 1_3298, 1_3373, 1_3389, 1_3316, 1_338...",0
31,5obm_20,/n/holylfs06/LABS/mzitnik_lab/Lab/afang/ATOMIC...,"1,2","[2_1673, 2_1669, 2_1736, 2_1672, 1_2302, 2_172...",0
32,5obm_28,/n/holylfs06/LABS/mzitnik_lab/Lab/afang/ATOMIC...,5,"[5_2413, 5_2406, 5_2811, 5_922, 5_2403, 5_2412...",0
33,5obm_29,/n/holylfs06/LABS/mzitnik_lab/Lab/afang/ATOMIC...,5,"[5_34, 5_33, 5_922, 5_811, 5_907, 5_809, 5_810...",0
34,5obm_49,/n/holylfs06/LABS/mzitnik_lab/Lab/afang/ATOMIC...,"5,8","[5_2383, 5_2991, 5_3000, 5_2996, 8_5, 5_419, 5...",0
35,5obm_50,/n/holylfs06/LABS/mzitnik_lab/Lab/afang/ATOMIC...,7,"[7_45, 7_23, 7_29, 7_51, 7_56, 7_60, 7_53, 7_3...",0
36,5obm_54,/n/holylfs06/LABS/mzitnik_lab/Lab/afang/ATOMIC...,"5,8","[8_108, 8_140, 8_118, 5_14, 8_141, 8_114, 8_10...",0
37,8oeq_3,/n/holylfs06/LABS/mzitnik_lab/Lab/afang/ATOMIC...,"1,B","[B_1658, 1_2092, 1_2095, B_1715, 1_1909, 1_194...",1
38,8oh6_8,/n/holylfs06/LABS/mzitnik_lab/Lab/afang/ATOMIC...,"1,B","[1_2082, B_1713, 1_2085, B_1661, 1_2083, B_166...",1
39,8oh6_11,/n/holylfs06/LABS/mzitnik_lab/Lab/afang/ATOMIC...,"1,4","[1_1491, 1_1522, 4_140, 1_1587, 1_1582, 4_109,...",1
40,8oh6_13,/n/holylfs06/LABS/mzitnik_lab/Lab/afang/ATOMIC...,B,"[B_1032, B_1062, B_1027, B_1021, B_1034, B_107...",1
41,8oi5_17,/n/holylfs06/LABS/mzitnik_lab/Lab/afang/ATOMIC...,1,"[1_1607, 1_1676, 1_1688, 1_1593, 1_1667, 1_176...",1
42,8oi5_30,/n/holylfs06/LABS/mzitnik_lab/Lab/afang/ATOMIC...,"1,4","[4_43, 4_109, 4_135, 4_137, 4_45, 4_104, 4_112...",1
43,8oi5_35,/n/holylfs06/LABS/mzitnik_lab/Lab/afang/ATOMIC...,B,"[B_1026, B_1063, B_1025, B_1058, B_1028, B_102...",1

In [ ]:
# Prepare RNAFM data
embeddings_dir = DATA_DIR + "/RNA_Ligand"
model_name = "rinalmo"

for split in ["train", "val", "test"]:
    split_df = pd.read_parquet(f'{DATA_DIR}/RNA_Ligand/RNA_Ligand_{split}_input.parquet')
    split_df.head()

    # Load embeddings
    embeddings_df = pd.read_parquet(f'{DATA_DIR}/RNA_Ligand/RNA_Ligand_sequences.parquet')
    embeddings_path = f"{embeddings_dir}/RNA_Ligand_embeddings_{model_name}.npy"
    tokens_path = f"{embeddings_dir}/RNA_Ligand_tokens_{model_name}.npy"
    with open(embeddings_path, "rb") as f:
        embeddings = np.load(f)
    with open(tokens_path, "rb") as f:
        tokens = np.load(f)
    assert tokens.shape == embeddings.shape[:-1]
    assert len(embeddings) == len(embeddings_df)

    embeddings_id_to_index = {(row['pdb_id'], row['chain_id']): i for i, row in embeddings_df.iterrows()}

    # Extract embeddings for each split
    split_embeddings = []
    for i, row in split_df.iterrows():
        pdb_id = row['pdb_id'].split("_")[0]
        curr_embeddings = []
        for chain_id in row['chain1'].split(","):
            index = embeddings_id_to_index[(pdb_id, chain_id)]
            embedding_ = embeddings[index]
            tokens_ = tokens[index]
            # start = np.where(tokens_ == 0)[0][0]
            end = np.where(tokens_ == 2)[0][0]
            curr_embeddings.append(np.mean(embedding_[:end], axis=0))
        split_embeddings.append(np.mean(curr_embeddings, axis=0))
    split_embeddings = np.array(split_embeddings)
    assert len(split_embeddings) == len(split_df)
    labels = np.stack(split_df['label'].tolist())

    np.save(f'{DATA_DIR}/RNA_Ligand/RNA_Ligand_{split}_embeddings_{model_name}.npy', split_embeddings)
    np.save(f'{DATA_DIR}/RNA_Ligand/RNA_Ligand_{split}_labels_{model_name}.npy', labels)

# Prepare for ATOMICA data input

In [55]:
pdbs = set()

dataset_paths = [
    f'{DATA_DIR}/RNA_Ligand/dataset',
    f'{DATA_DIR}/RNA_Site/dataset',
    f'{DATA_DIR}/RNA_Protein/dataset',
    f'{DATA_DIR}/RNAGo/dataset'
]

for dataset_path in dataset_paths:
    dataset_pdbs = os.listdir(dataset_path)
    dataset_pdbs = set([fname.split("_")[0] for fname in dataset_pdbs])
    pdbs.update(dataset_pdbs)

In [ ]:
with open(f'{DATA_DIR}/rnaglib_pdbs.txt', 'w') as f:
    f.write(",".join(pdbs))

In [58]:
f'{DATA_DIR}/rnaglib_pdbs.txt'

'/n/holylfs06/LABS/mzitnik_lab/Lab/afang/ATOMICA/baselines/rnaglib_tasks/rnaglib_pdbs.txt'